### ISSUE TITLE
Diamonds consumed even when Crystallize fails

### ISSUE THREAD

**Issue by zjdtmkhzt** [Mithion/Mana-And-Artifice#100]
When using a crystallize spell on a mob, it seems the diamond is consumed even when the spell fails due to the mob being too powerful.
As the failed spell yields no crystal, this means your diamond will be lost.

**Comment by Mithion** [comment]
This was fixed in 1.2.1.6 (beta on CurseForge).  It now works as follows:

All spells are now aware of their components' success or failure to apply.
Instant target spells such as bolt and touch will check this and not consume reagents if the spell misses.  Projectile or channelled spells attempt to apply their effect multiple times and as such will always consume the reagent whether they hit or miss.

This is much easier programatically, it makes sense thematically (you use the diamond/bonemeal/whatever to create the projectile itself and send it out, and it gives more use to shapes like touch.
