### ISSUE TITLE
Add a default divination highlights tag with Suspicious Sand and Suspicious Gravel

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#1014]
**Is your feature request related to a problem? Please describe.**
The primary issue is that there's no way to acquire Suspicious Sand and Suspicious Gravel in vanilla + MnA, so you can't ever use Divination to highlight it.

**Describe the solution you'd like**
It would be good to have a tag outside of the forge ores tag that blocks could be added to for default divination highlighting, since adding things to the forge ores tag can introduce unfortunate cross mod weirdness. This solution also opens up options for packmakers.

**Describe alternatives you've considered**
I've considered datapacking a recipe to make Suspicious blocks craftable. 

**Additional context**
This is mostly me looking forward to when Curiosities get added to MagiChem.

**Comment by Mithion** [comment]
At the risk of sounding dismissive, this is a "not my problem" issue - if a block is not obtainable, then it cannot be divined, and that's by design.  It's the same reason ores don't divine ore blocks, it's a rabbit hole that will result in the need for constant updates to that tag list, which I don't want to do.  My recommendation would be to find another mod that actually allows these blocks to be obtained so they can be divined.
