### ISSUE TITLE
[True invincibility] [1.2.1.6] Mob aggro works arbitrary

### ISSUE THREAD

**Issue by LiSirNo** [Mithion/Mana-And-Artifice#109]
True invisibility hide yours model and items but mobs aggro react arbitrary to it (I hope video will explain the problem). I don't know if this is balancing act but I could not find any rule to it or explanation in codex so here is report.

edit: video seems to be "white out" on website but seems to do fine after downloading

https://user-images.githubusercontent.com/9516113/103655403-78b0a380-4f67-11eb-9c7d-03588087a41f.mp4

**Comment by Mithion** [comment]
Mobs will still react if you get close enough (as per vanilla invisibility rules), but their target on you will be removed if you are more than 3 blocks away.  This may not be a perfect solution, but it's about as good as it's gonna get since the AI targeting tasks don't have a Forge event and I don't want to use mixins.

It also helps hide you from other players.

**Comment by Mithion** [comment]
(as of 1.2.1.7)
