### ISSUE TITLE
Using Arcana Book Turns My Font And Other Ui Elements To Black

### ISSUE THREAD

**Issue by HabibMughal1936** [Mithion/Mana-And-Artifice#127]
When I Use Arcana It Turns Day To Night But Also Glitches The Font And Huds I Am Using Texture PAcks And Shaders Too But With Some Shaders It Dissapears The Font And Huds By Using Arcana Please Help

**Comment by BlueAmulet** [comment]
@Mithion The HUD calls GL11.glPushAttrib and GL11.glPopAttrib which is causing the RenderSystem to go out of sync with the actual hardware state. I patched out these calls from the HUD code and now graphics are no longer imploding and the font no longer turns black or invisible.

**Comment by Mithion** [comment]
That's strange:  I always thought that the pushAttrib and popAttrib worked like pushMatrix and popMatrix, where it would simply allow you to preserve the attribute stack to actually prevent this from happening or calls to glColor3f for example from overriding the previous render state.

Is there an alternative that's able to do that, or am I just misunderstanding what's possible?

**Comment by BlueAmulet** [comment]
The thing that's causing the massive glitching with optifine shaders is specifically the drawing of the magic level on the mana bar. The idea is that, the RenderSystem has it's own copy of the GL state so it can avoid redundant operations like setting a specific blend mode when it was already set to that before. But if you're side stepping the RenderSystem and using direct GL11 calls, it is no longer aware of what the actual GL state is, and becomes out of sync.

You shouldn't need to call pushAttrib or popAttrib yourself, everything else will automatically set up the GL state as needed and the RenderSystem will automatically avoid redundant operations for performance.

Also as far as pushMatrix and popMatrix goes, I believe you're also not supposed to be calling GL11.glPushMatrix() or RenderSystem.pushMatrix() anymore but rather the matrixStack.push()/pop() functions, as well as matrixStack.translate()/rotate()/scale() instead of the respective functions on GL11 or RenderSystem.

**Comment by Mithion** [comment]
That makes sense.  I was still beholden to the old mindset of render events where you take all precautions to not disturb the gl state (or try to), so I thought the attrib calls would be helping.

I did use the matrix stack calls wherever available, and just assumed they hadn't implemented the attrib calls on that yet, as based on depreciation annotations they seem to be doing a rewrite.

I'll remove the attrib calls then and see how it does!

**Comment by Mithion** [comment]
So there's more to it than simply removing those calls; rendering the items causes the rest of the hud to darken (not entirely but it's hard to see unless you toggle it on and off).

I'll probably need to make some additional RenderSystem calls to change lighting or something, but either way I've removed the GL direct calls.

**Comment by Mithion** [comment]
Closing this as I've decided not to support Optifine, especially given that native shaders are coming in 1.17.
