### ISSUE TITLE
Manaweave Projector doesn't send shape to Manaweaving Altar when activated by non-user

### ISSUE THREAD

**Issue by VorpalLemur** [Mithion/Mana-And-Artifice#139]
Version: 1.2.1.9

I'm trying to automate the manaweaving altar and I'm playing using the direwolf20 modpack for 1.6.4. 

I've found no way to get a construct to add or remove items from the manaweaving altar.  Nor will hoppers add or remove items to/from the altar.   I have however found that I can use the Activator Module in a Modular Routers item router to add or remove items from the altar.  Great.   Now all I need to do is get a manaweave projector to issue the correct shapes.

I've found that I can use the Activator Module in a Modular Routers item router to trigger a manaweave projector to emit its shape.  However, this shape does not then get picked up by the manaweaving altar, instead it just hangs in the air.   Mana drains from the projector (which then gets refilled by a nearby mana crystal), the shape displays in the air, but the altar doesn't pick it up.  If I trigger the projector manually, the shape gets picked up by the altar just fine.

If I use a construct to trigger the same manaweave projector, then the altar will pick up the shape fine. 

I've also tried using a Cyclic Item User and have the same results... the projector gets triggered but the Altar won't pick up the shape.

The workaround I've found has been to send a timed redstone pulse to a lodestar which causes a construct to trigger the projectors at the right time.

**Comment by Mithion** [comment]
That's intentional functionality.

Manaweave patterns need to know who created them in order to apply progression limiting.  Without this, you'd be completely able to bypass tier limits, making the automation create patterns that you haven't unlocked yet.

Constructs are able to do it because they maintain a reference to their owner and will pass that along for this very purpose, meaning that it can be automated while still retaining tier limitations.  And, this functionality is lost when the owner goes offline, because there's no longer a player to reference.

Any kind of activator will need to pass along a valid player reference in order for the pattern to be consumed.
