### ISSUE TITLE
Constructs void items

### ISSUE THREAD

**Issue by MatthiasMann** [Mithion/Mana-And-Artifice#176]
Using mana-and-artifice-1.3.0.2 and forge-1.16.5-36.0.46

I noticed that an animated construct (with one hammer arm, one grabber arm, 8x air affinities) tasks with putting items into a rune forge which already contains another item will void the item.

The Lodestone had the following setup:
1. take item from chest (unfired rune plate)
2. place in runic forge
3. take item from runic forge
4. place on top of rune forge
5. chisel run (ritual one)
6. take childed rune (no filter)
7. place in anvil
8. take item from chest (super heated vintium ingot)
9. place on anvil
10. forge rune
11. take item from anvil (no filter)
12. place item in chest

As the rune forge takes a few seconds to heat the ingot, the construct proceeded and tried to chisel a rune (which failed as he had no blank one). The rest of the program continues and I saw that each time one unfired was taken and based on TOP the rune forge only contained one item.

If a construct can't place the item in hand in an inventory as instructed I think the item should be dropped on the ground instead (maybe the construct could also complain somehow by playing a sound or particle effects?).

**Comment by Mithion** [comment]
I had this issue reported to me differently but it was related to runes of marking going into a chest - I fixed it so that constructs won't void items in the next version.

I want to avoid dropping items on the ground as they have a time limit and could expire if the player isn't around.  Part of the challenge of construct logic is accounting for that and working around it, but they definitely shouldn't void items!

**Comment by Mithion** [comment]
1.3.0.3 fixed this issue
