### ISSUE TITLE
crystal of memories infinite xp

### ISSUE THREAD

**Issue by ungabunga1** [Mithion/Mana-And-Artifice#192]
if you take some xp from the crystal, use it for enchanting or something, then put the remaining xp back into the crystal it will have the same amount of xp as you started out with. Say you start out with a crystal that has 5000 xp, you take 3000xp, use 2000 xp, and then return the 1000 xp you have left back into the crystal, the crystal will go back to having 5000 xp.

**Comment by Mowmaster** [comment]
Since this item stores XP as durability, any mod that can repair durability (eternal stella from forbidden arcanus) basically gives you unlimited XP, of course storing the xp as something other then durability would fix this, not sure about the other bug, that one has been around for a while in lots of mods if i recall.

**Comment by Mithion** [comment]
This has been fixed in 1.4.0.0 and will go out with the next release.
