### ISSUE TITLE
[1.16.5-1.3.0.6] Potion Hut can float on top of plants or hang off ledges

### ISSUE THREAD

**Issue by TelepathicGrunt** [Mithion/Mana-And-Artifice#204]
This is especially noticeable in swamp biomes. Not sure if other M&A structures also has the same behavior as getting structures to spawn in a very low area is not common. It is quite strange looking lol. No parts of the structure's bottom actually touches the terrain
![image](https://user-images.githubusercontent.com/40846040/112665466-7a388c00-8e31-11eb-9694-4d95f8cc1991.png)

**Comment by TelepathicGrunt** [comment]
Looks like it also occurs when the structure spawns on ledges as well.
![image](https://user-images.githubusercontent.com/40846040/112665975-08ad0d80-8e32-11eb-9f94-df5dc9f718dc.png)

**Comment by Kymithi** [comment]
This particular structure needs the airspace below filled in with dirt (or something similar) and to be moved one blow down relative to the surrounding terrain. This wouldn't solve the structure appearing in improbable locations, but it would cause structures that otherwise spawn in good locations to be level with the ground and have no airspace below them.

**Comment by Mithion** [comment]
This has been resolved in later versions.
