### ISSUE TITLE
Item and text disapear

### ISSUE THREAD

**Issue by Dragonir44** [Mithion/Mana-And-Artifice#216]
When I have a wand or a spell in my hand, all text and items became invisible and return visible when I close the inventory. For the spell, when I right click with it in hand, the scroll open up but nothing appear on it.
![image](https://user-images.githubusercontent.com/69081570/114166085-92c69d00-992d-11eb-9f68-67b60a5d7cfb.png)
![image](https://user-images.githubusercontent.com/69081570/114166115-9eb25f00-992d-11eb-92b4-3d166049ea3e.png)

**Comment by ProphecyOak** [comment]
I had the same issue when clicking the codex whatever for the first time

**Comment by ProphecyOak** [comment]
Seems to be an issue with the HUD because when I change the settings for it by hitting the X in the book, it goes away when the HUD is disabled.

**Comment by TheVoidLord** [comment]
![2021-04-30_16 57 37](https://user-images.githubusercontent.com/61397361/116764203-3529eb80-a9d5-11eb-9048-83069485e240.png)
![2021-04-30_16 57 31](https://user-images.githubusercontent.com/61397361/116764206-36f3af00-a9d5-11eb-8faf-f5febbedf20c.png)

Same as above, if I turn the HUD for the mod completely off, the bug goes away. This also happens when I have any spell in hand. no way to get rid of it besides disabling HUD, even tried disconnecting and reconnecting.

**Comment by Mithion** [comment]
Remove optifine and the problem goes away.

**Comment by TheVoidLord** [comment]
I don't have optifine installed, so there's no need to close the issue

**Comment by Mithion** [comment]
Minimap mods can also cause the issue.  

Doesn't happen with just M&A and several other mods, so yeah there is a need to close the issue.

I've heard that Xaeros I think setting the layer to 5 or some such works.

**Comment by TheVoidLord** [comment]
Well. In that case, maybe ask instead of assuming it was Optifine. Thank you for the advice on Xaeros, that is helpful, as that i DO have installed.

**Comment by Mithion** [comment]
Its optifine in 90% of the cases and therefore a reasonable assumption.
