### ISSUE TITLE
Crystalize Projectile spell failure voids the diamond

### ISSUE THREAD

**Issue by abadger** [Mithion/Mana-And-Artifice#237]
mana-and-artifice: 1.3.0.6
mod pack: Direwolf20-1.16 v1.9.0

Created a Projectile::Crystalize::Speed spell.  Using the spell and missing the target creature results in the diamond reagent being voided.

**Comment by Mithion** [comment]
Hey sorry it took me so long to get back to you on this!
Crystallize is intended to consume the diamond when the spell spawns a targeting entity (so anything channeled or projectile, etc).
It's somewhat of a technical limitation due to how spell reagents work.

However, if you use touch or bolt, it will only consume the diamond when the effect is applied successfully (and not if you miss).
