### ISSUE TITLE
self and emanate shapes do not set affinities for construct crafting

### ISSUE THREAD

**Issue by abadger** [Mithion/Mana-And-Artifice#242]
I created two spells: self::slowfall and emanate::entangle Neither of these can be cast onto a chimerite crystal to set an affinity for construct crafting.  Thinking about it, self::slowfall makes some sort of sense since it is cast on oneself rather than the world around.  emanate could be similar as it's centered on oneself... but it's more of a stretch.  Both of these were surprising when I first tried.  Maybe the construct crafting and/or shape pages could have some text that explains which shapes do not work with construct crafting.

**Comment by Mithion** [comment]
That's intentional - the shape must directly target the block for it to set the affinity (like you said, self makes sense for that reason...as for emanation/wave/wall/etc):

The reason being is that when a block has special code for when a spell targets it, it cancels the rest of the spell's effect (to prevent unwanted side effects and replace the spell's effect on that block with the special effect instead).  What this means is that a single crystal could negate an emanation and be abused to create unintentionally and exceptionally powerful "defenses".

However I agree that the codex could be more clear about that part of the crafting process.

**Comment by Mithion** [comment]
The codex has been updated in 1.4.0.0 and will go out with the next release.

**Comment by abadger** [comment]
Thanks!
