### ISSUE TITLE
Lodestar reorganization and Nether Portals

### ISSUE THREAD

**Issue by Sleeclow** [Mithion/Mana-And-Artifice#291]
Thought of two new things that I feel may be helpful to have included in the mod (at least in my opinion).

 Firstly It would be fantastic if we could move the points around in the loadstar, so if we wanted to add a new function halfway through the existing setup, we could add in the new function, say a pick up from chest, and slide it along the existing line to be earlier, instead of having to delete everything before where we want the new function to be, and then setting up everything after all over again.

The other idea was it would be really nice if the portals from this mod worked across dimension, I wanted to set up a portal room below my tower, with a portal to a different location for each of the motes, only to realize I can't open a portal from this mod to the nether, so if I do it how I wanted I'd have to open a portal from this mod, to take you to the nether portal, to then take you into the nether.

**Comment by Mithion** [comment]
A lodestar overhaul is on my long list of things to do for the mod, but interdimensional portals already exist!
There's an item called a World Charm that you can use to attune to the dimension you're in, and then the Ritual of Return and the Ritual of the Gate can accept a world charm.  Doing so will cause them to look for the given rune combination in that dimension instead of their current dimension.

Homestead combinations are per-dimension, so you can have the same combination in the nether and in the overworld and use a world charm to pick which one to go to.

The world charm is not consumed by the ritual of return as well, so it works great inside a ritual kit.

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release (1.18.1)
