### ISSUE TITLE
Mana and Artifice Manaweaving Altar not working while having FastSuite installed

### ISSUE THREAD

**Issue by sirben99** [Mithion/Mana-And-Artifice#293]
Hey! 

While having FastSuite installed, Manaweaving Altar doesent work, meaning no ritual can be done we with it. FastSuite dev sayd Mana and Artifice has to fix this on theyr end, since its closed source

More info here: https://github.com/Shadows-of-Fire/FastSuite/issues/6

Ben

**Comment by Mithion** [comment]
Hey there,

In looking at the fastsuite dev's comment, they don't provide any actual information on how to fix the conflict.  Since they're the one modifying core forge functionality it falls to them to provide details.  My recipes work just fine without fastsuite so it stands to reason that their mod may not play nice with custom recipes.

If they provide some actual context or details on what's needed, or even an attempt to work on it, I'd be happy to work towards compatibility.  But the instant close just because M&A isn't open source doesn't give me much hope.

I'm going to close this for now, if you get more details feel free to comment and I'll look into it.
