### ISSUE TITLE
Config for Structures/Ore Gen

### ISSUE THREAD

**Issue by notWaterGuy12** [Mithion/Mana-And-Artifice#320]
I'm working on a modpack and was hoping for control of the world gen to be in the configs. Would love to see it for both structures and ore gen if possible. Thank you for your work on the mod, absolutely fantastic to play with!

**Comment by notWaterGuy12** [comment]
Config for entity spawns would also be greatly appreciated

**Comment by Sindusk** [comment]
I'd like to also request that an option be added to configure the ore and flower generation. At the very least, a toggle on/off, nothing more. This is important because it allows usage of other oregen mods such as [Large Ore Deposits](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits) to control the distribution of resources instead. In my specific case, I'd like to have ores and flowers generate in a different dimension, and not in the overworld. In the current version of Mana and Artifice, this isn't possible and poses a serious issue.

**Comment by Mithion** [comment]
Configs for entities and oregen were added in 1.5.0.x
