### ISSUE TITLE
A few suggestion

### ISSUE THREAD

**Issue by Hequinoxe** [Mithion/Mana-And-Artifice#325]
**Is your feature request related to a problem? Please describe.**
No frustration, just suggestion

**Describe the solution you'd like**
A few comments to provide feed back on the mod. Please understand that I adore Mana and Artifice and in no way I want to diminish it. To me it's the best magic mod out there, I just want to give a bit of input as a user just in case this inspire to more greatness.

A. Magic wand/staff
As a suggestion: maybe those that are looted could be restricted to useful variation. Maybe I was unlucky but the vast majority of the staffs I looted on multiples worlds were either harmful or did nothing (self crystallize, wave of rifts for example... out of my head not really what I literally looted, those I don't remember).
Another suggestion: Those that you make yourself; I understand the esthetic value could be interesting for some people but there's a drawback to these staves; you cannot put the spell in a spellbook or grimoire or rote book, perhaps we could have some enchants that could be added to the staff/wand or that there would be a rebate on mana cost. If I go wild: there could be specific enchants for those staves/wands for mana rebate, buff/debuff boost (magnitude), duration, range, etc. Kind of the alteration to spell but without the added mana cost/complexity

B. Summons
The whole concept is nice, there's just one issue I met; having the focus (I don't remember the exact name) in your inventory is kind of messy, you really need to make sure you do not kill the wrong mob; a cow is not as useful in combat as a skeletton. Maybe having it in your second hand while you kill the mob? Also the possibility of overwriting the mob would be nice in case of a mistake

C. Rift/inventory space
I love the idea of the Rift and I see it as reasonable for it's tier. But there's not really anything in the higher tier that would superseed it. I know that vanilla minecraft offer solution to this (ender chest/shulk box/etc.) but I would find value in having something with a lot more space like a greater rift. Or something akin to the greater collector ring (tp stuff into chests elsewhere) but instead of break, directly from inventory. 

D. Magic sword
I am confused by this sorcery type; I made in creative mode a sword of slow and a sword of lightning. Damage for both were 7. The only difference came when I added damage to the lightning sword, it overwrote the base damage. Mana was used on the lightning sword as if it was the lightning damage. In order to make it beneficial to use a damage spell as a sword, I would suggest adding the damage. For example on fire, frost, lightning, arcane damage; the base 7 damage + damage of the spell. Also, for the bow, I do not see the benefit of using the bow instead of the projectile. Especially since the "arrow" is invisible.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Mithion** [comment]
Hey there,

No offense taken at all; I welcome suggestions (just note I won't add them all :) )

A. The idea behind looted magic staves are that you're finding old experiments by wizards in the past, so not all of them are going to be useful.  I've found some _insanely_ powerful staves, and I've found others that aren't all that useful.  It does limit them somewhat, for example bound weapons won't be on looted staves as that doesn't actually function; but my lore behind it does account for some of them being less than useful.

As for player crafted staves, one of their main benefits are the ability to accept enchantments like beheading, smite, bane of arthropods, etc.  They're great for a backup option if you run out of mana, or if something is particularly magic resistant like a witch.  I typically have my main attack spell on a staff with a few enchantments and it works great.

New enchants for staves I'm not sure on...need to think about this more.  I don't want to give them too many benefits as I want it to mainly be an aesthetic choice while leaving regular spells as a more or less equivalent option.

B. Requiring the phylactery to be in the offhand is a solid idea, I like it.  Helps limit mistakes.  As for emptying it, a simple craft recipe is also a good idea (maybe with an additional small material cost).

C. Not fully sure what you're getting at with the Greater Collector Ring interaction with Rift here, but I feel the amount of portable storage is completely reasonable, especially since you can store things like ritual kits in them which accept any item.  No reason you can't use them as a backpack :)

D. The swords are mainly intended to have the sword damage and a secondary debuff like slow or weakness.  The other damage types benefit allows it to scale higher than 7 damage of the sword as well as the secondary effects (like arcing lightning).  It's also one of the only ways to have physical damage on a spell.  

Bound Bow arrows aren't invisible, they're just hard to see from the shooter's perspective.  You can see this for yourself by strafing as you fire.  Using projectile is fine too; remember that some players like to play with an RP feel or a certain aesthetic.  Not everything needs to be better than everything else :)  Bound bow shots also intentionally don't have an associated baseline damage so you can do things like healing arrows and the like.

**Comment by Hequinoxe** [comment]
Thanks for the rapid response.

A. For the looted magic staves; ok I undertsand better. I must not have been lucky.
For the player created one: I was not aware that we could have enchants on it. I will try that for sure. I think you are right that too much benefits would be OP vs regular spells.

C. I had not realised that I could use ritual kits that way but now that you mention it it makes sense. Then yes the amount of portable storage is good. Just to clarify my initial idea even if it is not relevant: The greater collector ring allows to send broken block into a chest if you have a marker in your second hand. I was thinking that a same concept but from inventory; if you have a marker related to a chest in your second hand when you cast the "greater rift" you could send items from your inventory to the chest but not take anything from it. 

D. I understand better now thanks.

**Comment by Mithion** [comment]
Empty phylacteries will now only be filled if they are in the main hand or off hand.

**Comment by Mithion** [comment]
Fixed with the release of 1.5.0.0
