### ISSUE TITLE
Mana and Artifice projectiles causing severe lag in force loaded chunks

### ISSUE THREAD

**Issue by Dandas52** [Mithion/Mana-And-Artifice#326]
**Describe the bug**
When chunks are force loaded, Mana and Artifice mobs can spawn thousands of projectiles, causing the game to crash as soon as a player walks near a certain area. I have confirmed this to happen with both Witch Hunter arrows and Skeleton assassin shurikens, as I have had to /kill thousands of both entity types in order to stop the lag. 

Additionally, it would help (if possible), if these entities could be made more identifiable to profilers and crash reports, as currently, they give no more information then "abstractArrowEntity", making it difficult to pinpoint the cause. 

**Expected behavior**
Projectile entities despawn rather than staying in the world indefinitely. 

**Crash report**
https://pastebin.com/HNMhxjqV

**Version Information (please complete the following information):**
 - Mod Version: 1.4.0.8
 - Forge Version 36.1.32

**Comment by Mithion** [comment]
Both of those are set to despawn after 3 seconds in the ground (or in a block).  They do this by overriding tickDespawn in AbstractArrowEntity and looking for a value of 60 ticks instead of the default 1200 ticks that arrows use.

Probably the result of them trying to hit a pixie and missing repeatedly, but the 3 seconds shouldn't generate thousands of them.

The change was only implemented in recent beta versions; can you confirm it's happening on 1.4.0.8 repeatedly and isn't a result of entities being stacked up in a previous version?

**Comment by Dandas52** [comment]
Yep, can confirm that the issue is happening consistently in 1.4.0.8. It may also help to note that the issue seems (thus far) exclusively happen in the Ratlantis dimension, although I am unsure whether or not this is simply a fluke.

**Comment by Mithion** [comment]
I've also flagged the arrows/shuriken as "no save", lowered their update interval, and decreased their tracking range.  This should help mitigate the issue as well.

**Comment by Dandas52** [comment]
Would it also be possible to provide a clearer indicator to profilers and crash logs about the identity of mana and artifice projectiles? They are difficult to track at the moment because they are presented simply as abstractArrowEntities without a mod identifier.

**Comment by Mithion** [comment]
They all use mod identifiers; not sure why your profiler is showing them as abstractArrowEntities.  For example, spells:
mana-and-artifice:spell_projectile
mana-and-artifice:witch_hunter_arrow
mana-and-artifice:witch_hunter_trickshot

I recently had to translate them because WAILA/One Probe/etc was showing these untranslated names.

**Comment by Mithion** [comment]
This has been fixed in dev and will go out with the next release (1.18.1).
