### ISSUE TITLE
Issues I Found with Staff of the Pilgrim

### ISSUE THREAD

**Issue by PhyrexianAgent** [Mithion/Mana-And-Artifice#331]
**Describe the bug**
You can not run over things like stairs and slabs and you can not crouch walk. If you try you will be unable to as if there was a full block there (or in case of crouch walking being completely unable to move, only able to look around until you stop crouching). When you restart the game with the effect removed, this issue stops until you equip, then unequip the staff.

**To Reproduce**
1. Get item 'Staff of the Pilgrim'
2. Equip 'Staff of the Pilgrim'
3. Unequip 'Staff of the Pilgrim' and wait for the effect to end
4. Attempt to walk over a stair or slab or walk while crouching

**Expected behavior**
You should be able to walk over the stair or slab as normal (in case of crouch walking being able to move at all).

**Version Information (please complete the following information):**
 - Mod Version: 1.4.0.0 (also in 1.3.0.6)
 - Forge Version 36.2.2

**Additional context**
Other Mods: Tinker's Construct, Save My Stronghold, Swing Through Grass, Biomes O' Plenty, JEI, Abnormals Core, Buzzier Bees, Berry Good, Flywheel, Curios API, Patchouli, Mantle, Create, Yung's Better Caves, Waystones, Forge Ender Tech, Placebo, Yung's API, Environmental. Corail Tombstone, Fast Furnace, Vampirism, Teamlapin Library, Vampirism Integrations, Waila, Allurement, Pollution of the Realms, Illagers+, The Twilight Forest, Dynamic Trees, Dynamic Trees for Vampirism, Dynamic Trees for Biomes O' Plenty, Yung's Better Mineshafts, BetterEnd Forge

**Comment by Mithion** [comment]
Do you have another mod that does step assist (changes the step height of the player)?  I'm not familiar with all of these mods.

**Comment by PhyrexianAgent** [comment]
Not really since none of these mods i am pretty sure manipulate with things like stairs and slabs at all. also this seems to effect any difference in height (above the block the player stands on) as dirt paths are also effected by this issue (trying to go off the path to a block beside it that is not the path).

**Comment by PhyrexianAgent** [comment]
i decided to properly check by removing all the mods except yours and the 2 library mods yours needs. seems the issue is gone after i did that

**Comment by PhyrexianAgent** [comment]
after troubleshooting what mod is causing the issue it is environmental (note its dependancy abnormals core by itself does not cause the issue) (also note i just had environmental abnormals core and your mod and dependancies meaning environmental by itself is with your mod causing the issue)

**Comment by Mithion** [comment]
So to do step assist there are 2 ways to go about it:  additive and absolute.  Both work fine when it's only one mod doing it, however absolute often causes conflicts.

Absolute works like this:
 - item equipped/potion used/etc.
 - step height = 1.6
 - item removed/potion expired/etc.
 - step height = 0.6

Additive works like this:
 - item equipped/potion used/etc.
 - step height = step height + 1
 - item removed/potion expired/etc.
 - step height = step height - 1

I use additive to try to remain as compatible as possible.  So if another mod flat out overwrites the step height value instead of applying a modifier, then mine subtracts, it can set the step height to 0 resulting in your issue.  It's tricky because step height is just a number; there's no surrounding modifier system surrounding it (like there is with things like health or move speed), and so it's very easy to run into conflicts like these.

I've put in code to ensure that when my pilgrim buff expires, it won't let the step height go below 0.6 (the MC default).  This should help avoid these kinds of conflicts in the future.

This is considered fixed in dev for next release.

**Comment by Mithion** [comment]
Fixed with the release of 1.5.0.0
