### ISSUE TITLE
"Summon Workbench" is not usable for crafting

### ISSUE THREAD

**Issue by flarn2006** [Mithion/Mana-And-Artifice#368]
**Describe the bug**
When using "Summon Workbench", attempting to craft anything will result in the output slot remaining empty, as if the recipe were invalid.

**To Reproduce**
1. Obtain a "Summon Workbench" spell.
2. Cast the spell, and (if applicable) right-click the summoned crafting table.
3. Attempt to craft something.
4. Observe that the recipe doesn't work.

**Expected behavior**
I assume it's supposed to work like a standard crafting table, allowing me to craft all the same things.

**Screenshots**
I didn't take one and I'm not in-game right now (it takes a long time to load) but I feel like the issue I'm describing is clear enough that a screenshot is unnecessary. Please let me know if you would like me to take one anyway.

**Version Information (please complete the following information):**
 - Mod Version: 1.4.0.8
 - Forge Version: 1.16.5-forge-36.2.4

**Additional context**
FTB University modpack version 1.3.0

**Comment by Mithion** [comment]
![image](https://user-images.githubusercontent.com/2482373/145912808-c1d31de3-ee47-4643-9071-40d45a8a55e2.png)

Just M&A and dependencies, works fine - likely a mod incompatibility.  You'll need to start removing mods until the issue is gone.
I know mods like fastsuite tend to have issues with M&A, perhaps that might be a place to start.
If you end up finding the incompatibility or working with the pack author to find it, please let me know.
