### ISSUE TITLE
Suggestion: Method to "refresh" Thaumaturgic Compass

### ISSUE THREAD

**Issue by Timelife** [Mithion/Mana-And-Artifice#445]
I noticed that the Thaumaturgic Compass points to the closest indicated world feature from the point of creation, and the only way to refresh the compass to point to a new location is by performing the ritual of locating again with another thaumaturgic link consumed. Would it be possible to have a method implemented that allowed the compass to be refreshed without consuming the same type of link, such as right clicking the compass or by another ritual like "Ritual of the Shaking Compass" that would be a very small ritual that consumed the original compass and perhaps one piece of arcane ash?

Also, a dedicated bag to hold thaumaturgic links would be nice, with a search feature if possible (a search feature on the wandering wizard would also be wonderful).

**Comment by Mithion** [comment]
Wandering wizard got search functionality - so that one's done at least :)
A refresh ritual like you mentioned is a good idea - I'll give it a ponder and see what I can come up with.

The new Practitioner's Pouch can be used to hold links, but really the intended design is to summon the wandering wizard and search there for the links you want as the ritual to summon him and the links themselves are all very inexpensive.

I think if the compass could be refreshed, there wouldn't be a need for a dedicated bag/container for links.

**Comment by Mithion** [comment]
This was added in later versions.
