### ISSUE TITLE
Conflict with mod "illagers wear armor"

### ISSUE THREAD

**Issue by Mad-Gnome** [Mithion/Mana-And-Artifice#458]
**Describe the bug**
With Mana and Artifice installed when I update the mod "Illagers Wear Armor" from 1.1.0 to 1.1.1 game crashes on startup every-time.  If I downgrade their mod to 1.1.0 it goes away.

**To Reproduce**
Illagers 1.1.1
Mana and Artifice 1.7.0.5
Forge 39.0.85

**Expected behavior**
I was expecting them to work together, they worked together just fine with "Illagers Wear Armor" 1.1.0

**Screenshots**
Crash message "Error: java.lang.IllegalStateException: Failed to load description for particle mna:arcane_random"

Full Crash Log: https://pastebin.com/ktJ63pn3

**Version Information (please complete the following information):**
Illagers 1.1.1
Mana and Artifice 1.7.0.5
Forge 39.0.85

**Additional context**
I realize this bug only happens when I update Illagers Wear Armor, but the crash description points to M&A (in my limited understanding).  I posted this bug report on their Issue tracker as well.

**Comment by Mithion** [comment]
Weird.  The descriptor for the "arcane_random" particle is in there; I checked.
I also see Optifine in there; it could be that as well.

In case for whatever reason it's missing, this is the contents of the arcane_random.json file that should go into /assets/mna/particles:

{
  "textures": [
    "mna:sparkle"
  ]
}

Since updating Illagers Wear Armor caused the crash; I'm going to assume it's something they did and close this for now - however if it does indeed turn out to be M&A, this can be re-opened for further investigation.
