### ISSUE TITLE
Bug: After death magic level and tier resets (Problem when playing with goki stats)

### ISSUE THREAD

**Issue by Lendoker** [Mithion/Mana-And-Artifice#461]
**Describe the bug**
I was playing with my friend and he died, after it we saw that tier, magic level and faction were reseted (It's because of goki stats, so fix it please)

**To Reproduce**
Die while having any magic lvl and goki stats installed

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.5.1.7] 1.16.5

**Comment by Lendoker** [comment]
It only works with goki stats, and I dunno why it's happening, but when I die with goki stats, minecraft thinks that I've never opened the guide book and never upgraded oculus or had a magic level (I think it's problem with mana and artifice, not with goki stats)

**Comment by Mithion** [comment]
My theory is that goki stats is interfering with the events that M&A uses to copy data to the new player entity from the old one after respawn.

Since this works just fine with all kinds of other mods including ones that handle death events (corpse, tombstone, etc) but only goki stats; I'm assuming it's something they're doing, and therefore something they'll need to fix.

If it turns out it is an M&A issue, then this can be re-opened for further investigation.  However I'm going to close it for now to keep the queue clean.
