### ISSUE TITLE
Occulus Tasks related to crafting not working

### ISSUE THREAD

**Issue by SheepSheepington** [Mithion/Mana-And-Artifice#484]
**Describe the bug**
When a player on my server crafts objects for the Tier 1 Occulus tasks (Manaweaving Wand, Manaweaving Altar, Inscription Table, none of the others) it removes the progress made on those randomly. The other players can progress as normal.

**To Reproduce**
I'm not entirely sure why this is happening for only some users.
1. Do the tasks to Craft Manaweaving Altar
2. Leave and rejoin the game.
3. Progress will be lost. For this one player... Also, they cannot complete all the tasks then sleep to complete it in one sitting. I think it's not being tracked at all.

**Expected behavior**
When you craft the items, you will get the progress

**Version Information (please complete the following information):**
 - Mod Version: [e.g. 1.5.1.7]
 - Forge Version [e.g. 36.2.31]

**Additional context**
Playing with the All the Magic: Spellbound

**Comment by ArtOfCombat** [comment]
Same issue here, same modpack, also on a server.

**Comment by Mithion** [comment]
This is usually due to using modded tables, which don't fire the proper crafting events.  Using a vanilla table or the magicians workbench will cause the correct events to be raised.

I recommend encouraging mod authors to raise the ItemCraftedEvent within forge when things are crafted at their modded tables to promote interoperability.
