### ISSUE TITLE
[1.18.2] The Spellbreaker entity lags server, tps down to 7. (Spark profiler included.)

### ISSUE THREAD

**Issue by Gbergz** [Mithion/Mana-And-Artifice#516]
**Describe the bug**
The Spellbreaker entity lags server to shreds, tps down to 7.

**To Reproduce**
Not sure exactly, but have a spellbreaker entity in world.

**Expected behavior**
For the entity not to lag and bring down tps.

**Version Information (please complete the following information):**
 - Mod Version: 1.7.2.3
 - Forge Version: 40.1.48

**Additional context**
Spark Profiler report: https://spark.lucko.me/eV7otSH0AW

Edit: Also to add onto this, tried disabling them from spawning, but the config doesn't work. 
And disabling the spawn with In Control mod doesn't work either.

**Comment by Gbergz** [comment]
Update: It's really bad. TPS at 5 now.

**Comment by jojobmomo** [comment]
Having the same issue, singleplayer world FPS drops to 1 when a spellbreaker spawns... Running 11900k and a 3090 so i know its not me...

**Comment by ProsperCraft** [comment]
We are having the same problem, when a spellbreaker renders FPS drops.  mna-1.7.2.4

**Comment by JustJinxed** [comment]
This is also happening on the Direwolf20 modpack (ver 1.6.1). I'm on a SMP, and it seems both the clients and server are having issues. Pretty sure this is indeed a mod interaction, because it's not happening when I startup with just JEI and MNA running. I'm almost betting it's [AI-Improvements](https://www.curseforge.com/minecraft/mc-mods/ai-improvements).

**Comment by ProsperCraft** [comment]
We don't have AI improvements in TownCraft, so less likely to be that one.

**Comment by JustJinxed** [comment]
> We don't have AI improvements in TownCraft, so less likely to be that one.
In JUST as I edited lol. I'll xref with TownCraft. We'll figure it out.

**Comment by JustJinxed** [comment]
So I couldn't figure out why the first time I tried doing this with MNA alone, I didn't seem to get lag, but now I'm getting hit hard every time. (Only MNA, Gecko, and Curio API loaded) I'm below Y level -40, in creative mode, summon a Spell Breaker, and I can literally play hide and seek by where the lag happens. Seems to only trigger when looking towards the Spell Breaker. (MNA 1.7.2.6)

**Comment by Mithion** [comment]
![image](https://user-images.githubusercontent.com/2482373/181332854-9c2c6acc-4668-4140-ba4f-0b75ffc78222.png)
Not getting any kind of lag spikes when looking at a spell breaker.

@JustJinxed can you post a link to the pack you're using?  I'll try installing it to check.  Also since you've replicated the error, can you please check to see if it happens with any other M&A mobs?

Lastly, what versions of Curios and GeckoLib are you using to replicate this error?

**Comment by JustJinxed** [comment]
I haven't noticed the lag with any other mobs at all, at least not to such a degree where it's this noticeable. 

Working in the Direwolf20 Pack (v. 1.6.1) [It's a FTB pack](https://feed-the-beast.com/modpack/95_ftb_presents_direwolf20_1_18)
geckolib-forge-1.18-3.0.25
curios-forge-1.18.2-5.0.7.1

Going to include my startup string since I'm down to the barebones 3 mods when replicating this. 
-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
Using JDK 18.0.1.1

**Comment by JustJinxed** [comment]
FOUND IT!! geckolib was updated in one of my tests, and not in anything after the fact. The entire issue seems to be with an outdated library of all things. Updating to geckolib-forge-1.18-3.0.29 fixes the issue. Given their changelog it makes perfect sense too. 

> v3.1.10
> - Update GeoArmor Item.
> - Update Core
> - Tweaked Entity Render
> - Updated Leash Code - sharffffff
> - Ticking Tweak

**Comment by Mithion** [comment]
Amazing, good find!  Closing this as resolved, but this is great as now I can also inform folks who are having the same issue what the fix is.

**Comment by Sanya268** [comment]
Can somebody help me?
I'm having same issue, but on version 1.19.2
Is in this version bug still exists?
