### ISSUE TITLE
Spellweaver Armor Flight not being maintained when Self repairing.

### ISSUE THREAD

**Issue by TheAgentFlash** [Mithion/Mana-And-Artifice#518]
**Describe the bug**
The Spellweaver armor's flight gets turned off every time it repairs itself

**To Reproduce**
1. Wear full set of spellweaver armor in survival
2. Have it get damaged
3. Try to fly and get canceled when it repairs using your mana

**Expected behavior**
To be able to maintain flight while it repairs.

**Version Information**
 - Mod Version: [1.7.2.3]
 - Forge Version [40.1.31]

**Additional context**
Side note, When I wear said armor and cast mist form, the flight speed of the armor overrides the flight speed of mist form.

**Comment by optmisticnihilist** [comment]
Same flight damage issue with Druidic Armor, Forge 40.1.51, Mod 1.7.2.3. Possibly due to the flight abilities being enchantments of the armor. 

Would changing the flight abilities to be effects, like being near a Mana Crystal, work?

Or for lore purposes, you could say that too much damage break the concentration needed for maintaining flight.

**Comment by UAVwaffle** [comment]
I also have the same issue, I am using the latest version
