### ISSUE TITLE
[1.18.2] Fey Courts Ritual of Sanctum Invocation - missing objects in guide and adding those blocks does not complete the build (potential mod conflict?)

### ISSUE THREAD

**Issue by CinnaMonday** [Mithion/Mana-And-Artifice#529]
**Describe the bug**
I'm running the Donutcraft modpack (version 1.0.6) with the current latest version of MNA manually installed. When building the structure for the Fey Courts sanctum, the Codex Arcana does not mention that four lanterns are required to complete the build; these only appear in the multiblock visualization when I'm building it. Additionally, when I added l added those lanterns, the structure did not register as complete.

**To Reproduce**
1. Create a world in Minecraft 1.18.2, using the Donutcraft 1.0.6 modpack (with MNA 1.7.2.5 manually installed).
2. Join the Fey faction and perform the Ritual of Sanctum Invocation.
3. Attempt to build the fey faction structure - around step 4, the multiblock visualization begins to display that lanterns are required to complete the structure, despite the materials list in the Codex Arcana not listing them.
4. Upon adding lanterns to their respective spots in the visualization, they are not recognized as required blocks and do not add to the final count of blocks needed to complete the structure. The block count is stuck at 250/254, despite having added the lanterns.

**Expected behavior**
Upon adding the lanterns, the ritual would be registered as complete and players allied with the Fey faction would receive their respective benefits.

**Screenshots**
![ritualmaterials](https://user-images.githubusercontent.com/108843000/177665926-d7684f54-990a-41d6-bcce-7a1ce8d7f330.jpg)
The Fey sanctum materials list in MNA 1.7.2.5.
![2022-07-06_19 33 25](https://user-images.githubusercontent.com/108843000/177665948-ab3c396e-b8f7-4d12-a27c-c84c85ce9bdb.png)
Multiblock visualization for the sanctum, showing lanterns that need to be placed.
<img width="925" alt="feysanctum1" src="https://user-images.githubusercontent.com/108843000/177665961-6de1e408-300c-4b2e-bcb2-3efcc3333d30.png">
Additional screenie showing where to place a lantern, with a block count for the structure.
<img width="887" alt="feysanctum2" src="https://user-images.githubusercontent.com/108843000/177665971-2de59688-1fcc-4d61-a070-815cbb52e547.png">
Sanctum after adding a lantern - the block count does not change. These ghost lamps will forever haunt me.

**Version Information:**
 - Mana and Artifice Mod Version:  [1.7.2.5]
 - Forge Version:   [40.1.25]
 - MC Version:  [1.18.2]
 - Additional Lanterns Mod Version:  [1.0.1]

**Additional context**
The version of Donutcraft that I'm running includes the Additional Lanterns mod (1.0.1), which changes the vanilla Minecraft lantern to an Additional Lanterns lantern when placed in the world. However, the AL vanilla lantern still uses the `minecraft:lantern` registry, so I imagine that it would still be read as a vanilla lantern. Not sure if the mods are conflicting with one another, but I felt that it was worth mentioning nonetheless.

Thank you very much! Anything that could steer me in the right direction would be greatly appreciated.

**Comment by Mithion** [comment]
It does appear to be a conflict with Additional Lanterns - I'm not sure why they're overwriting the base lantern item, but that does appear to be the root cause.

It does work without additional lanterns:
![image](https://user-images.githubusercontent.com/2482373/178787166-85b3ea04-802a-40f2-bd06-a0c47b47c503.png)

There is a way to datapack the multiblocks in M&A to allow variants (for example, if  you look at recipes/multiblock/wellspring_capture.json there is a section called "replacements" which allows you to define alternate blocks at given offsets from the structure root.

I have a command in dev that will generate this for me, so here's the JSON you'll need (replace 'minecraft:coal_ore' with whatever the lantern block is and give it a unique variation id where shown):

```
{
  "data": [
    {
      "offset": {
        "X": 2,
        "Y": 3,
        "Z": 5
      },
      "state": {
        "Name": "minecraft:coal_ore"
      }
    },
    {
      "offset": {
        "X": 3,
        "Y": 3,
        "Z": 2
      },
      "state": {
        "Name": "minecraft:coal_ore"
      }
    },
    {
      "offset": {
        "X": 6,
        "Y": 3,
        "Z": 3
      },
      "state": {
        "Name": "minecraft:coal_ore"
      }
    },
    {
      "offset": {
        "X": 5,
        "Y": 4,
        "Z": 5
      },
      "state": {
        "Name": "minecraft:coal_ore"
      }
    }
  ],
  "id": "variation_id_here_must_be_unique"
}
```

You can use this to make a datapack that will override the multiblock with variants that will accept the modified lanterns.

Alternatively, you can build out the structure with the changed lanterns and save out the NBT using a Structure Block, and make a datapack to override the structure NBT itself.  The rest of the mod should adapt accordingly.
