### ISSUE TITLE
Pose stack not empty crash

### ISSUE THREAD

**Issue by ArcaneSan** [Mithion/Mana-And-Artifice#676]
**Describe the bug**
When running latest MnA and Epic fight (EF 20.6.3) on MC 1.20.1 the game will crash after loading up a world for about 10-20 seconds.

**To Reproduce**
1.  Load world (new or old)
2. Wait for about 30ish seconds
3. Game crashes

**Expected behavior**
World to not crash.

**Version Information (please complete the following information):**
 - Mod Version: 1.20.1-3.0.0.4-all
 - Forge Version [47.2.16]

**Additional context**
Crash does not happen when downgrading MnA to version 3.0.0.3, asked first in the epic fight discord and they did not see anything that was related to Epic fight
Also does not happen with just MnA

https://mclo.gs/cai4VUu

latest.log

**Comment by dawntreader03** [comment]
This also happens when attempting to ride specifically the dragons from the Ice and Fire: Dragons mod. Other mounts work fine, just the dragons that are crashing the world.  Unless I downgrade from the current version of Mana And Artifice (both latest and 3.0.0.4-all manifest this) to 3.0.0.3. Then mounting the dragons becomes possible.

Crash log below. Thank you!

[crash-2024-01-24_05.59.18-client.txt](https://github.com/Mithion/Mana-And-Artifice/files/14030158/crash-2024-01-24_05.59.18-client.txt)
