### ISSUE TITLE
Crash when hovering over an enchanted projection rune

### ISSUE THREAD

**Issue by Darknesszin** [Mithion/Mana-And-Artifice#706]
**Describe the bug**
Crash when hovering mouse over the projection enchanted rune

**To Reproduce**
1. use disenchanter to transfer enchantment over to the projection rune
2. hover cursor over rune
3. Crash

**Expected behavior**
Name and description should appear

**Screenshots**
![Screenshot_59](https://github.com/Mithion/Mana-And-Artifice/assets/95110081/6ba7ef5e-f8b9-4316-aa03-f1d6bf938759)

**Version Information:**
 - Mod Version: 3.0.0.9
 - Forge Version 47.2.20

**Additional context**
https://hastebin.com/share/afinitipex.php CRASH LOG
[latest.log](https://github.com/Mithion/Mana-And-Artifice/files/14366043/latest.log)

**Comment by Mithion** [comment]
![image](https://github.com/Mithion/Mana-And-Artifice/assets/2482373/348730f1-b5d3-4a33-a753-7787835a83c3)
Works fine with just M&A.
This will be a conflict with one of your mods in your pack - you will need to identify which one it is before a fix can be made.

On the discord we keep a list of known incompatibilities; that may be a good starting point, or you can try a binary search approach to narrow down which mod is doing it.  A common issue is embeddium, that might be another good starting point.

**Comment by dawntreader03** [comment]
Exact same error happens with mine. Though this also happens not just with hovering over projection enchanted runes while on inventory, it also happens when hovering over enchantment runes in the codex.

Mods included in my personal pack are, but not limited to:
-Dragon Magic and Relics
-Factions and Curiosities
-Blood Magic
-Aether and addons
-Occultism
-Theurgy
-Create and addons
-Twilight Forest
-Goety
-Primal Magick
-JEI and addons

Tested with all these installed and with MnA alone = no error
Tested with Embeddium AND addons = no error
Tested with MnA and a new MnA Addon, Magichem = error

Hope this information helps.

I'm not a programmer so I'm not sure what "res" is in the error report but something between Magichem and MnA is trying to invoke that "res", probably something with Darknesszin's pack as well. Probably Magichem and a mod in poster's pack is trying to do something to that 'res' in particular that's causing MnA to error when present.

Crash log below.

https://pastebin.com/AYbW18M0

**Comment by dawntreader03** [comment]
Sorry, I forgot to mention.

That latest crash log was produced with only MnA and Magichem.

MnA version: 3.0.0.9
Forge version: 47.2.20

Again, I hope this helps.

**Comment by Mithion** [comment]
I did put a fix in for this in 3.0.0.10 (or 11) - can you confirm if the issue is still happening?
