### ISSUE TITLE
Ritual of Location and structure location is too unclear, buggy and user-anti-friendly

### ISSUE THREAD

**Issue by uhloin** [Mithion/Mana-And-Artifice#803]
Version mna-forge-1.20.1-3.0.0.14-all.jar 

1. There is Ritual of Location and it required Thaumaturgic Link. But there is no receipt how to craft it (in the JEI) or such text in Codex to find. Need to google to know I must buy it from wandering wizard. Also Just Enough Resources mod does not show this as possible purchase.
2. If perform Ritual of Location with usual Compass, I get the a usual Compass as result, I can stack it with other usual compass and cannot see any "enchanting" on it. Compass points to north, not to requested structure.
3. There is some Thaumaturgic Compass, but again, no receipts, no info, even impossible to buy from wizard.
4. Wizard becomes invisible if summoned at night like wandering trader even if there are no enemies around.
5. Wizard disappears too quickly,
6. Wizard trade UI is glitchy (dirt pixels in search field)
7. Wizard trade UI is not convenient, non-standard and not intuitive. Need random clicking to get something.
8. Even if create Dowsing Rod from Thaumaturgic Link on Manaweaving Altar, this rod doesn't work and points to bed instead of requested structure.

**Comment by ShelLuser** [comment]
So, context: I'm just a fellow fan who just so happens to have started playing 2 days ago with my friend. Therefor I feel I can relate, _especially_ because we've just been through this ourselves!

With all due respect, but I don't fully agree with some of your arguments.

1) First: it's not uncommon for 'modded Minecraft' in general to have certain items without a recipe. And while I fully agree that being able to search would make things a bit better, it's also fair to say that there's a hint right in the documentation for the Locating ritual itself: "_Trade with the wandering wizard summoned by the aptly named ritual (ommited) to get **most** of the locating patterns_". It's all right there.

2) I / we cannot reproduce that issue. It's meant to be done with a regular compass which is then enchanted / changed into a thaumurgic compass. If the mod glitched for you at this point I can easily understand your confusing / frustration. Still, can't reproduce any errors here.

4) Yups, we can reproduce this one. I can see that this can be annoying but... to be fully honest I also think it's fitting at the same time. I mean, it matches the behavior of any other wanderers so....

5) So maybe prepare more thoroughly?  Don't mean to sound harsh here but it's mentioned right in the codex itself that this guy will only stay for a minute or so. While I can agree that this could make things a bit harder, it's _also_ fair to say that this little bit of pressure makes the encounter more special. Just for context: my gf had no clue what to expect so after summoning she had to grab the ingots, then go back to the trader and yet she could still trade 3 - 4 items without any issues.

7) In our opinion that also makes it stand out. This is just our take on this but ... the wizard isn't there for your convenience, he's doing you a favor. Like being allowed in a store, but it'll up to you to find what you need because it.

8) That's documented in the codex: if you only hold the rod in your hand it'll do that. You need to hold something in your _other_ hand, something which represents the structure (or thing) you're looking for. For example (I quote): rune of marking, player charm or chimerite gem.
