### ISSUE TITLE
Villgers

### ISSUE THREAD

**Issue by DinnerBeef** [Mithion/Mana-And-Artifice#91]
I am trying to get enchanted books from a villager. But your mod seem to be adding trade for Mana weaving Patterns to the Librarian  and  that is not allowing enchanted books to come up in its trades.

**Comment by Mithion** [comment]
The mod re-balances something I consider to be an oversight in vanilla, in that level 1 librarians can sell enchanted books.  This goes against all of the previous bugfixing in vanilla surrounding villager trades indicating that it was overlooked.  It's an exploit to continually re-roll the same librarian for cheap enchants that you'd otherwise have to work for.

I changed it so that librarians don't sell enchanted books at Level 1 or 2 anymore, but still will at Level 3.

That being said, I know not everyone will agree with me, so if you look in the mod's config there is an option to turn that part off.  It still adds the patterns making enchants more rare though, there is no config for that.

**Comment by VT-14** [comment]
Being able to roll the dice on a fresh villager's first trades is intended (https://bugs.mojang.com/browse/MC-150777).  This ability with Librarians has been well known since the 1.14 snapshots, and Mojang could easily change the Enchanted Book to be a later trade tier if they thought it was too OP.  They even tweaked a Librarian Trade to address the exploit of buying bookshelves, breaking them, and selling back the books to gain Emeralds (https://bugs.mojang.com/browse/MC-153334).

I agree that the ability is rather powerful, but I do think it's fully intended by Mojang (it's less random than the Enchantment table, but it's rather tedious and time consuming, and uses far more XP overall).  I personally think that config should be disabled by default.  I really don't like mods quietly changing such vanilla features by default.  If I hadn't heard rumors that Mana and Artifice was doing that, it could have taken me hours to track down this 'feature' to disable it.

**Comment by X66Herobrine66X** [comment]
Agreed. Please change it back or at least make the config option disabled by default. This changing of vanilla mechanics simply because you don't like them is seriously unprofessional.

**Comment by Mithion** [comment]
Funny, it's almost like it's my mod and I can do what I want.  I don't owe you "professionalism" nor do I care if you think I am or not.
