### ISSUE TITLE
Ritual of the Ancient Coucil

### ISSUE THREAD

**Issue by KH3Sora** [Mithion/Mana-And-Artifice#97]
on the dw20 pack I did the ritual and nothing happened all the animations played and I goot placed back on the ground but I didnt get my tier up like you are meant to

**Comment by KH3Sora** [comment]
> on the dw20 pack I did the ritual and nothing happened all the animations played and I goot placed back on the ground but I didnt get my tier up like you are meant to

additional info this was on 1.1.1 on a server

**Comment by Mithion** [comment]
What mod version?
Did the occulus tell you that you're ready to advance and to use that ritual?
Single player or server?

**Comment by KH3Sora** [comment]
version 1.2.0.2
I had done all tasks for Tier 2 and it told me to do one of the 3 rituals to advance, it was on a private server.

**Comment by Mithion** [comment]
I just tried it in 1.2.0.5 and it worked perfectly - perhaps it was a conflict with another mod.  I'll have to install the DW20 pack and see.

If needed, you can have an op run the following commands:

/setTier 3 KH3Sora
/setFaction ANCIENT_WIZARDS KH3Sora

That will set you where you need to be in order to continue.

**Comment by KH3Sora** [comment]
thanks, we did that anyway as it was in the book, really dont know what caused it. it even have been server lag right as it was supposed to finish causing it not to detect it. dont know of anyone else on the server that is messing with the mod though . thanks anyway
