### ISSUE TITLE
Light Pylon lights cannot be replaced and block interaction

### ISSUE THREAD

**Issue by AranaiRa** [Mithion/Mana-And-Artifice#971]
**Describe the bug**
Lights created by the Light pylon cannot be replaced by other blocks, nor can they be targeted for breaking effects. The light will also block any attempts to right click "through" a space containing a light.

**To Reproduce**
1. Set up a Light Pylon
2. Attempt to place a block where a light is
3. Attempt to right click a block while a light block is in between you and your target

**Expected behavior**
Light blocks are unobtrusive and don't interfere with block placement / interaction.

**Version Information (please complete the following information):**
 - Mod Version: 3.1.0.1

**Comment by Mithion** [comment]
I just tried this, and was easily able to replace a light and click through it.

Checked, and the lights have no voxel shape so they can't block clicks, and they're set to be replaceable with no condition.  I don't remember if I changed this since last release, so making this comment for informational purposes and marking the issue as fixed in dev.

**Comment by Mithion** [comment]
This was resolved in 3.1.0.2
